updating logger to latest
gobuffalo/mw-paramlogger pull request #1
Opened 2018-08-03 14:20 UTC by paganotoni

2018-08-04 04:19 UTC, mclark4386 requested changes
Just a reminder of the changes requested in the other repo^^

2018-08-04 04:19 UTC, mclark4386 commented on param_logger.go
> +	blacklist []string
Just to point it out here as well, so it's not forgotten, @markbates want this changed to `exclusionlist` as well.

2018-08-04 04:19 UTC, mclark4386 commented on param_logger.go
> +		blacklist: ParameterExclusionList,
Also here.

2018-08-04 04:19 UTC, mclark4386 commented on param_logger.go
> +		pl.blacklist = ParameterExclusionList
Which means these and below will need to change as well ... probably best to do a find and replace in this case^^

2018-08-04 04:19 UTC, mclark4386 commented on param_logger_test.go
> +		blacklist: []string{
Don't forget here^^

2018-08-06 09:33 UTC, stanislas-m commented
@paganotoni I've changed things in your PR, can you confirm it still works the way you want?

I've tried to refactor it so it's closer to the original, and since all the config is handled by `ParameterExclusionList`, ther eis no need to create a whole structure for that. Thoughts?

2018-08-07 08:20 UTC, stanislas-m commented
I've reverted my changes, and updated from latest upstream version.

2018-08-07 08:20 UTC, merged